### ISSUE TITLE
V 0.6.0 ?

### ISSUE THREAD

**Issue by willemx** [splendido/meteor-moment-twix#3]
...any chance of a publishing new version ?
Thanks for maintaining a Meteor-package of this lib!

**Comment by splendido** [comment]
...I've just tried by simply update the git submodule, but it's no more working...
I'll have to dig a bit more.

**Comment by splendido** [comment]
[Here](https://atmospherejs.com/splendido/moment-twix) you go!

...I think I'll make a PR to the official repo for official meteor integration.
So it may be that this package will soon be unmigrated ;-)

**Comment by splendido** [comment]
Let me know if it works as expected!

...I've quickly tested it, and it should :)

**Comment by willemx** [comment]
It works...
splendid job!

**Comment by splendido** [comment]
:)

**Comment by splendido** [comment]
...done!

Please see https://atmospherejs.com/icambron/twix
...and the [ongoin attempt](https://github.com/icambron/twix.js/pull/55) to get an official integration through [autopublish.meteor.com/](http://autopublish.meteor.com/)

**Comment by splendido** [comment]
we eventually have the official pubblication!!!
See [momentjs:twix](https://atmospherejs.com/momentjs/twix)

Tnx
